export const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";
export const SYNC_ADDRESSES = "SYNC_ADDRESSES";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
