export const SYNC_WISHLIST = "SYNC_WISHLIST";
export const EMPTY_WISHLIST = "EMPTY_WISHLIST";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
