export const UPDATE_BRANDS = "UPDATE_BRANDS";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_MINIMUM_RATING = "UPDATE_MINIMUM_RATING";
export const TOGGLE_AVAILABILITY_PREFERENCE = "TOGGLE_AVAILABILITY_PREFERENCE";
export const RESET_FILTERS = "RESET_FILTERS";
